spring:
  application:
    name: Ana Fit Service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost/anafit}
    username: ${DATABASE_USER:regulatorio}
    password: ${DATABASE_PASSWORD:regulatorio}
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: update
  security:
    debug: true

logging:
  level:
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
    org.springframework.web: ${WEB_LOG_LEVEL:DEBUG}

security:
  jwt:
    secret-key: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}