spring:
  application:
    name: Ana Fit Service
  datasource:
    username: regulatorio
    url: jdbc:postgresql://localhost/anafit
    password: regulatorio
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000